name: mariac_pocket_env
channels:
  - defaults
dependencies:
  - pip=25.1
  - python=3.13.5
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - pre-commit==4.2.0
      - pytest==8.4.1
      - pytest-cov==6.2.1
      - ruff == 0.12.9
      - black == 25.1.0
